################################ Description ########################################################
# This function generates dataset with time-fixed covariates, each covariate
### follows the same distribution of that of the first pseudosubject generated by 
### the time-varying generation function.
#####################################################################################################
itct_term_tfPH <- function(beta,x1,x2,x3,x4,x5,x6){
  R1 = x1*x2-log(x3+x4)-x6/x5
  R2 = beta[1]*x1+beta[2]*x2+beta[3]*x3+beta[4]*x4+beta[5]*x5+beta[6]*x6
  R3 = cos(pi*(x1+x5))+sqrt(x6+x2)-x3
  R4 = -beta[1]*x1+beta[2]*x2-beta[3]*x3+beta[4]*x4-beta[5]*x5+beta[6]*x6
  R0 = (x4>=0.7)*((x5==2)+(x5==5))*R1+(x4>=0.7)*(1-(x5==2)-(x5==5))*R2+
    (x4<0.7)*((x5==2)+(x5==5))*R3 + (x4<0.7)*(1-(x5==2)-(x5==5))*R4
  return(R0)
}


Time_gnrt_PH <- function(data, Distribution, model, Coeff){
  x1 = data$X1
  x2 = data$X2
  x3 = data$X3
  x4 = data$X4
  x5 = data$X5
  x6 = data$X6
  u = data$U
  Alpha = Coeff$Alpha
  Beta = Coeff$Beta
  Lambda = Coeff$Lambda
  V = Coeff$V
  if (model == 4){
    Param = itct_term_tfPH(beta=Beta,x1,x2,x3,x4,x5,x6)
    Param = exp(Param)
    if (Distribution == "Exp"){
      TT = -log(u)/Lambda/Param
    } else if (Distribution == "WD"){
      TT = (-log(u)/Lambda/Param)^(1/V)
    } else if (Distribution == "WI"){
      TT = (-log(u)/Lambda/Param)^(1/V)
    } else if (Distribution == "Gtz"){
      TT = Alpha*(-log(u))/Lambda/Param
      TT = log(TT + 1)/Alpha
    } else {
      stop("Wrong distribution is given.")
    }
  } else if (model == 2){
    Param = exp(Beta[1]*x1+Beta[2]*x2+Beta[3]*x3+Beta[4]*x4+Beta[5]*x5+Beta[6]*x6)
    if(Distribution == "Exp"){
      TT = -log(u)/Lambda/Param
    }else if (Distribution == "WD"){
      TT = (-log(u)/Lambda/Param)^(1/V)
    }else if (Distribution == "WI"){
      TT = (-log(u)/Lambda/Param)^(1/V)
    }else if (Distribution == "Gtz"){
      TT = Alpha*(-log(u))/Lambda/Param
      TT = log(TT + 1)/Alpha
    }else {
      stop("Please check the distribution.")
    }
  } else if (model == 3){
    Param = exp(-log(x6+x3/10+x5/20+1/5)-x1*(x2*2)^(4*x4))
    if(Distribution == "Exp"){
      TT = -log(u)/Lambda/Param
    }else if (Distribution == "WD"){
      TT = (-log(u)/Lambda/Param)^(1/V)
    }else if (Distribution == "WI"){
      TT = (-log(u)/Lambda/Param)^(1/V)
    }else if (Distribution == "Gtz"){
      TT = Alpha*(-log(u))/Lambda/Param
      TT = log(TT + 1)/Alpha
    }else {
      stop("Please check the distribution.")
    }
  }
  
  result = list(Time = TT, Xi = Param)
  return(result)
}
#################################################################
Timefixed_gnrt_PH <- function(N = 300, model = 1, Distribution = "Exp", 
                                censor.rate = 1){
  Data <- as.data.frame(matrix(NA, N, 27))
  names(Data)<-c("I","ID","X1","X2","X3","X4","X5","X6","X7","X8","X9","X10", 
                 "X11","X12","X13","X14","X15","X16","X17","X18","X19","X20",
                 "Start","Stop","C","Event","Xi")
  ## time-invariant
  Data$X1 <- sample(c(0,1),N,replace=TRUE)
  Data$X2 <- runif(N,0,1)
  Data$X3 <- sample(c(0,1),N,replace=TRUE)
  Data$X4 <- runif(N,0,1)
  Data$X5 <- sample(c(1:5),N,replace = TRUE)
  Data$X6 = sample(c(0,1,2),N,replace=TRUE)
  Data$X7 <- runif(N,0,1)
  Data$X8 <- runif(N,1,2)
  Data$X9 <- sample(c(1:5),N,replace=TRUE)
  Data$X10 <- runif(N,0,1)
  Data$X11 <- sample(c(0,1),N,replace=TRUE)
  Data$X12 <- sample(c(0,1,2),N,replace=TRUE)
  ## time-varying 
  Data$X14 <- sample(c(1:5),N,replace = TRUE)
  Data$X15 <- runif(N,0,1)
  Data$X17 <- runif(N,0,1)
  Data$X19 <- sample(c(0,1),N,replace=TRUE) 
  Data$X13 = sample(c(0,1),N,replace=TRUE) 
  Data$X16 = sample(c(0,1),N,replace=TRUE) 
  Data$X18 <- sample(c(0,1,2),N,replace=TRUE)
  Data$X20 <- runif(N)
  
  Data$U <- runif(N)
  if (model == 4){
    Beta = c(1,1,-1,-1,0.5,-0.5)
    if (Distribution == "Exp"){
      Lambda = 0.05
      Alpha = 0
      V = 0
    } else if (Distribution == "WD"){
      Lambda = 0.14
      V = 0.5
      Alpha = 0
    } else if (Distribution == "WI"){
      Lambda = 0.0001
      #V = 2
      V = 1.8
      Alpha = 0
    } else if (Distribution == "Gtz"){
      Alpha = 0.1
      Lambda = 0.015
      V = 0
    } else {
      stop("Wrong distribution is given.")
    }
    
  } else if (model == 2){
    Beta <- c(1,1,-1,-1,0.5,-0.5)
    if(Distribution == "Exp"){
      Lambda = 0.003
      Alpha = 0
      V = 0
    }else if (Distribution == "WD"){
      Lambda = 0.012
      V = 0.8
      Alpha = 0
    }else if (Distribution == "WI"){
      Lambda = 0.001
      V = 2
      Alpha = 0
    }else if (Distribution == "Gtz"){
      Alpha = 0.1
      Lambda = 0.008
      V = 0
    }else {
      stop("Please check the distribution.")
    }
  } else if (model == 3){
    Beta = rep(0,6)
    if(Distribution == "Exp"){
      Lambda = 0.1
      Alpha = 0
      V = 0
    }else if (Distribution == "WD"){
      Lambda = 0.15
      V = 0.8
      Alpha <- 0
    }else if (Distribution == "WI"){
      Lambda = 0.0025
      V = 1.8
      Alpha = 0
    }else if (Distribution == "Gtz"){
      Alpha = 0.1
      Lambda = 0.02
      V = 0
    }else {
      stop("Please check the distribution.")
    }
  }
  Coeff = NULL
  Coeff$Alpha = Alpha
  Coeff$Beta = Beta
  Coeff$Lambda = Lambda
  Coeff$V = V
  
  for (Count in 1:N){
    RT = Time_gnrt_PH(data=Data[Count,], Distribution, model, Coeff)
    Data$Stop[Count] = RT$Time
    Data$Xi[Count] = RT$Xi
  }
  Data$Start <- 0
  Data$C <- 0
  Data$Event <- 1
  
  
  if(censor.rate == 0){
    Censor.time <- rep(Inf,N)
  }else if(censor.rate == 1){
    # only WI is changed!!!
    if (model == 4){
      if(Distribution == "Exp"){
        Censor.time = rexp(N,rate = 1/203)
      }else if(Distribution == "WD"){
        Censor.time = rexp(N,rate = 1/1768)
      }else if(Distribution == "WI"){
        Censor.time = rweibull(N,shape = 2, scale = 623)
      }else if(Distribution == "Gtz"){
        Censor.time = rweibull(N,shape = 2, scale = 48)
      }
    } else if (model == 2){
      if(Distribution == "Exp"){
        Censor.time = rexp(N,rate = 1/93)
      }else if(Distribution == "WD"){
        Censor.time = rexp(N,rate = 1/520)
      }else if(Distribution == "WI"){
        Censor.time = rweibull(N,shape = 2, scale = 48)
      }else if(Distribution == "Gtz"){
        Censor.time = rweibull(N,shape = 2, scale = 36)
      }
    } else if (model == 3){
      if(Distribution == "Exp"){
        Censor.time = rexp(N,rate = 1/153)
      }else if(Distribution == "WD"){
        Censor.time = rexp(N,rate = 1/282)
      }else if(Distribution == "WI"){
        Censor.time = rweibull(N,shape = 2, scale = 112)
      }else if(Distribution == "Gtz"){
        Censor.time = rweibull(N,shape = 2, scale = 37)
      }
    } else {
      stop("Wrong model type is used.")
    }
  }else if(censor.rate == 2){ ## NOT YET ADJUSTED
    if (model == 4){
      if(Distribution == "Exp"){
        Censor.time = rexp(N,rate = 1/59)
      }else if(Distribution == "WD"){
        Censor.time = rexp(N,rate = 1/9.5)
      }else if(Distribution == "WI"){
        Censor.time = rexp(N,rate = 1/35)
      }else if(Distribution == "Gtz"){
        Censor.time = rexp(N,rate = 1/50)
      }
    } else if (model == 2){
      if(Distribution == "Exp"){
        Censor.time = rexp(N,rate = 1/97)
      }else if(Distribution == "WD"){
        Censor.time = rexp(N,rate = 1/69)
      }else if(Distribution == "WI"){
        Censor.time = rexp(N,rate = 1/19)
      }else if(Distribution == "Gtz"){
        Censor.time = rexp(N,rate = 1/31)
      }
    } else if (model == 3){
      if(Distribution == "Exp"){
        Censor.time = rexp(N,rate = 1/30.8)
      }else if(Distribution == "WD"){
        Censor.time = rexp(N,rate = 1/132)
      }else if(Distribution == "WI"){
        Censor.time = rexp(N,rate = 1/15)
      }else if(Distribution == "Gtz"){
        Censor.time = rexp(N,rate = 1/15.8)
      }
    } else {
      stop("Wrong model type is used.")
    }
  }else{
    stop("Wrong censoring type")
  }
  
  for( j in 1:N){
    Vec <- c(0,Data[j,]$Stop,Inf)
    ID <- findInterval(Censor.time[j], Vec)
    
    if (ID <= 1){
      Data[j,][ID,]$C = 1
      Data[j,][ID,]$Event = 0
      Data[j,][ID,]$Stop = Censor.time[j]
    }
  }
  Data$I <- 1:nrow(Data)
  Data$ID <- 1:nrow(Data)
  RET = NULL
  RET$Data = Data
  RET$Info <- list(Coeff = Coeff, Dist = Distribution, Set = "PH")
  return(RET)
  
}
